# Generated by Django 3.1.7 on 2021-03-19 21:53

import django.db.models.deletion
from django.db import migrations, models

import delivery.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id',
                 models.PositiveIntegerField(primary_key=True, serialize=False,
                                             verbose_name='Идентификатор курьера')),
                ('courier_type', models.CharField(
                    choices=[('foot', 'Пеший'), ('bike', 'Велокурьер'),
                             ('car', 'Курьер на автомобиле')], max_length=4,
                    verbose_name='Тип курьера')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('assign_time', models.DateTimeField(auto_now_add=True,
                                                     verbose_name='Время выдачи курьеру')),
                ('expected_reward', models.PositiveIntegerField(
                    verbose_name='Ожидаемое вознаграждение')),
                ('courier',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='invoices',
                                   to='delivery.courier',
                                   verbose_name='Назначенный курьер')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code',
                 models.PositiveIntegerField(primary_key=True, serialize=False,
                                             verbose_name='Код района')),
            ],
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('name', models.CharField(max_length=11, primary_key=True,
                                          serialize=False, validators=[
                        delivery.validators.interval_validator],
                                          verbose_name='Интервал(HH:MM-HH:MM)')),
                ('begin', models.PositiveIntegerField(
                    verbose_name='Начало интервала в минутах')),
                ('end', models.PositiveIntegerField(
                    verbose_name='Конец интервала в минутах')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id',
                 models.PositiveIntegerField(primary_key=True, serialize=False,
                                             verbose_name='Идентификатор заказа')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4,
                                               validators=[
                                                   delivery.validators.weight_validator])),
                ('delivery_hours',
                 models.ManyToManyField(db_index=True, related_name='orders',
                                        to='delivery.TimeInterval',
                                        verbose_name='Часы работы')),
                ('region',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   related_name='orders', to='delivery.region',
                                   verbose_name='Район заказа')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('complete_time', models.DateTimeField(null=True,
                                                       verbose_name='Время завершения заказа')),
                ('delivery_time', models.PositiveIntegerField(null=True,
                                                              verbose_name='Время доставки в секундах')),
                ('invoice',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='invoice_orders',
                                   to='delivery.invoice')),
                ('order',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='invoice_orders',
                                   to='delivery.order')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='orders',
            field=models.ManyToManyField(db_index=True,
                                         related_name='invoices',
                                         through='delivery.InvoiceOrder',
                                         to='delivery.Order',
                                         verbose_name='Заказы'),
        ),
        migrations.AddField(
            model_name='courier',
            name='regions',
            field=models.ManyToManyField(db_index=True,
                                         related_name='couriers',
                                         to='delivery.Region',
                                         verbose_name='Районы доставки'),
        ),
        migrations.AddField(
            model_name='courier',
            name='working_hours',
            field=models.ManyToManyField(db_index=True,
                                         related_name='couriers',
                                         to='delivery.TimeInterval',
                                         verbose_name='Часы работы'),
        ),
    ]
