# Generated by Django 3.1.7 on 2021-03-13 12:59

import delivery.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор курьера')),
                ('courier_type', models.CharField(choices=[('foot', 'Пеший'), ('bike', 'Велокурьер'), ('car', 'Курьер на автомобиле')], max_length=4, verbose_name='Тип курьера')),
            ],
            options={
                'ordering': ('courier_type', 'courier_id'),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Код района')),
            ],
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=11, validators=[delivery.validators.interval_validator], verbose_name='Интервал(HH:MM-HH:MM)')),
                ('begin', models.PositiveSmallIntegerField(verbose_name='Начало интервала')),
                ('end', models.PositiveSmallIntegerField(verbose_name='Конец интервала')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор заказа')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, validators=[delivery.validators.weight_validator])),
                ('delivery_hours', models.ManyToManyField(db_index=True, related_name='orders', to='delivery.TimeInterval', verbose_name='Часы работы')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery.region', verbose_name='Район заказа')),
            ],
            options={
                'ordering': ('weight', 'order_id'),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_time', models.DateTimeField(auto_now_add=True, verbose_name='Время выдачи курьеру')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='delivery.courier', verbose_name='Назначенный курьер')),
            ],
        ),
        migrations.AddField(
            model_name='courier',
            name='regions',
            field=models.ManyToManyField(db_index=True, related_name='couriers', to='delivery.Region', verbose_name='Районы доставки'),
        ),
        migrations.AddField(
            model_name='courier',
            name='working_hours',
            field=models.ManyToManyField(db_index=True, related_name='couriers', to='delivery.TimeInterval', verbose_name='Часы работы'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='deliveries', serialize=False, to='delivery.order', verbose_name='Заказ в доставке')),
                ('complete_time', models.DateTimeField(null=True, verbose_name='Время завершения заказа')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='delivery.invoice', verbose_name='Накладная')),
            ],
        ),
    ]
