default:
  SECRET_KEY: ""
  DEBUG: true
  ALLOWED_HOSTS: []
  CORS_ALLOWED_ORIGINS: []
  DATABASE_URL: ""

development:
  DEBUG: true
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost

product:
  DEBUG: false
  ALLOWED_HOSTS:
    - 130.193.56.231
  CORS_ALLOWED_ORIGINS:
    - 127.0.0.1
    - localhost