default:
  SECRET_KEY: ""
  DEBUG: true
  ALLOWED_HOSTS: []
  CORS_ALLOWED_ORIGINS: []
  DATABASE_URL: ""
  IS_NEW_REGIONS_AND_TIME_INTERVALS_AVAILABLE: true

development:
  DEBUG: true
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - testserver

product:
  DEBUG: false
  ALLOWED_HOSTS:
    - 130.193.56.231
    - localhost
    - testserver